name: CI Процесс

on:
  push:
    branches: [develop, main, 'release/*']
  pull_request:
    branches: [develop, main, 'release/*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: JDK 17 Тохируулах
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Checkstyle, Тест, Coverage Шалгах
        run: mvn clean verify
